export interface DeepAnalyzeItem {
  /** Human readable name */
  readonly name: string;
  /** Stage whose output this item depends on */
  readonly dependsOn: import('../task.types').TaskStage;
  /** Files generated by this item */
  readonly outputFiles: string[];
  analyze(taskId: string, storage: import('../../local-storage/local-storage.service').LocalStorageService): Promise<void>;
}
