import { TaskStage } from '../task.types';

export interface TaskStageHandler {
  readonly stage: TaskStage;
  /**
   * Files generated by this stage. Used for dependency checks.
   */
  readonly outputFiles?: string[];
  handle(taskId: string): Promise<void>;
}
