import { TaskStage } from '../task.types';
import type { StageHandlerCtor } from './stage-handler.base';

export interface TaskStageHandler {
  readonly stage: TaskStage;
  /**
   * Files generated by this stage. Used for dependency checks.
   */
  readonly outputFiles?: string[];
  /**
   * Handler class whose output this stage depends on.
   * Using the class type allows stronger references
   * than plain string stage names.
   */
  /**
   * Classes of handlers this stage depends on. If multiple
   * handlers are required, list them all here.
   */
  readonly dependsOn?: StageHandlerCtor[];
  handle(taskId: string): Promise<void>;
}
